# Generated by Django 5.0.7 on 2025-08-22 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '習慣カテゴリ',
                'verbose_name_plural': '習慣カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='目標タイトル')),
                ('description', models.TextField(verbose_name='目標の詳細')),
                ('target_date', models.DateField(verbose_name='目標達成日')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '完了'), ('paused', '一時停止'), ('cancelled', 'キャンセル')], default='active', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='優先度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.habitcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '目標',
                'verbose_name_plural': '目標',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=200, verbose_name='行動名')),
                ('duration_minutes', models.IntegerField(verbose_name='継続時間（分）')),
                ('completed', models.BooleanField(default=True, verbose_name='完了')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.habitcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '行動ログ',
                'verbose_name_plural': '行動ログ',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='通知有効')),
                ('ai_feedback_frequency', models.CharField(choices=[('daily', '毎日'), ('weekly', '週1回'), ('monthly', '月1回')], default='daily', max_length=20, verbose_name='AIフィードバック頻度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('preferred_categories', models.ManyToManyField(blank=True, to='myapp.habitcategory', verbose_name='興味のあるカテゴリ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='提案日')),
                ('recommendation_type', models.CharField(choices=[('daily_goal', '日次目標'), ('habit_suggestion', '習慣提案'), ('motivation', 'モチベーション'), ('reflection', '振り返り')], max_length=50, verbose_name='提案タイプ')),
                ('title', models.CharField(max_length=200, verbose_name='提案タイトル')),
                ('content', models.TextField(verbose_name='提案内容')),
                ('reasoning', models.TextField(verbose_name='提案理由')),
                ('action_items', models.JSONField(default=list, verbose_name='具体的なアクション')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='優先度')),
                ('is_implemented', models.BooleanField(default=False, verbose_name='実装済み')),
                ('feedback_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='フィードバック評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'AI提案',
                'verbose_name_plural': 'AI提案',
                'unique_together': {('user', 'date', 'recommendation_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('mood_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='気分スコア')),
                ('energy_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='エネルギーレベル')),
                ('content', models.TextField(verbose_name='日記内容')),
                ('gratitude', models.TextField(blank=True, verbose_name='感謝の気持ち')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '日記',
                'verbose_name_plural': '日記',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
